---
booktitle: Proceedings of The 1st Conference on Lifelong Learning Agents
shortname: CoLLAs
volume: '199'
year: '2022'
start: 2022-08-22
end: 2022-08-24
published: 2022-11-28
conference_number: '1'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: CoLLAs-2022
month: 0
cycles: false
bibtex_editor: Chandar, Sarath and Pascanu, Razvan and Precup, Doina
editor:
- given: Sarath
  family: Chandar
- given: Razvan
  family: Pascanu
- given: Doina
  family: Precup
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 1st Conference on Lifelong Learning Agents
    Held in McGill University, Montr\'{e}al, Qu\'{e}bec, Canada on 22-24 August 2022

  Published as Volume 199 by the Proceedings of Machine Learning Research on 28 November 2022.

  Volume Edited by:
    Sarath Chandar
    Razvan Pascanu
    Doina Precup

  Series Editors:
    Neil D. Lawrence
date_str: 22--24 Aug
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v199"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v199
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v199
email: ''
conference:
  name: Conference on Lifelong Learning Agents
  url: https://lifelong-ml.cc/
  location: McGill University, Montréal, Québec, Canada
  dates:
  - 2022-08-22
  - 2022-08-23
  - 2022-08-24
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v199/collas_2022.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v199/collas_2022.bib
